/**
 * Generate the string modules the bundle needs but cannot import.
 *
 * The dsh host serves ONE script per plugin bundle, so neither the viewer's
 * stylesheet nor the PDF worker can be separate assets the page fetches:
 *
 *   - `src/ofv-style.ts`     — @open-file-viewer/core's stylesheet text
 *   - `src/pdfjs-worker.ts`  — pdfjs-dist's worker source, turned into a
 *                              blob URL at runtime so no bare specifier or
 *                              CDN fetch is involved
 *
 * Run: node scripts/gen-assets.mjs  (or `pnpm build`, which runs it first)
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const HEADER =
  '// GENERATED by scripts/gen-assets.mjs. Do not edit by hand:\n' +
  '// re-run `pnpm build` after upgrading a dependency.\n' +
  '//\n' +
  '// A string module, not an import: the host serves one script per bundle,\n' +
  '// so these bytes must travel inside client.js.\n'

/**
 * Write one source file as a default-exported string.
 * @param label - human name for the log line.
 * @param from - absolute path of the source file.
 * @param to - absolute path of the generated module.
 * @param wrap - whether to prefix the generated-file header.
 */
function emit(label, from, to, wrap = true) {
  const text = readFileSync(from, 'utf8')
  writeFileSync(to, `${wrap ? HEADER : ''}export default ${JSON.stringify(text)}\n`)
  console.log(`gen-assets: ${label} -> ${to} (${text.length} chars)`)
}

emit(
  'viewer stylesheet',
  fileURLToPath(new URL('../node_modules/@open-file-viewer/core/dist/style.css', import.meta.url)),
  fileURLToPath(new URL('../src/ofv-style.ts', import.meta.url)),
)

emit(
  'pdfjs worker',
  fileURLToPath(new URL('../node_modules/pdfjs-dist/build/pdf.worker.mjs', import.meta.url)),
  fileURLToPath(new URL('../src/pdfjs-worker.ts', import.meta.url)),
)
