/**
 * Open File Viewer preview for DSH.
 *
 * STANDALONE: this plugin depends only on DSH's own platform services
 * (`slots`, `sidebarRightTabs`, `remote`) and on `@open-file-viewer/core`.
 * It does not use, or require, any other preview plugin.
 *
 * It hooks the same seam DSH's own preview uses:
 *
 *   1. `sidebarRightTabs.register(definition)` declares a tab TYPE for the
 *      existing document kind. A kind with no type in force renders the
 *      platform's "nothing can view this" notice, so registering one is what
 *      makes file clicks open a preview at all.
 *   2. `slots.register({ name: 'sidebar.right.pane.tab', key: id }, Body)`
 *      supplies the body under that type's own `id`.
 *
 * File bytes are read straight from the platform's workspace Remote
 * (`readBytes`), paged because a complete-file read is refused above the
 * deployment cap (32 MiB by default) rather than truncated.
 */
import {
  createViewer,
  imagePlugin,
  videoPlugin,
  audioPlugin,
  textPlugin,
  pdfPlugin,
  officePlugin,
  archivePlugin,
  emailPlugin,
  drawingPlugin,
  xmindPlugin,
  cadPlugin,
  model3dPlugin,
  gisPlugin,
  epubPlugin,
  xpsPlugin,
  ofdPlugin,
  assetPlugin,
  fallbackPlugin,
} from '@open-file-viewer/core'
import type { PreviewPlugin } from '@open-file-viewer/core'
// React is a host platform seed: the build keeps this external and the
// generated `require("react")` resolves through the client module table.
import { createElement, useEffect, useRef, useState } from 'react'
// pdfjs is bundled, never resolved at runtime: a bare `import("pdfjs-dist")`
// cannot resolve in the browser (there is no node_modules lookup), and the
// viewer's own `workerSrc` default points at a jsDelivr CDN. Passing the
// module explicitly is the documented escape hatch
// (`options.pdfjs || await import(...)` in renderPdfDocumentPreview).
import * as pdfjs from 'pdfjs-dist'
// The worker's source text, generated by scripts/gen-assets.mjs. pdfjs wants
// a URL, so it becomes a blob URL at runtime — same-origin, no network.
import pdfjsWorkerSource from './pdfjs-worker'
// The stylesheet as a string module, generated by scripts/gen-assets.mjs.
import ofvCss from './ofv-style'

const STYLE_ATTR = 'data-dsh-open-file-viewer'
let styleInstalled = false

/**
 * Pane CSS, kept local so the layout survives the host's theme. It travels
 * inside the same <style> as the viewer's own stylesheet — never as a `style`
 * prop, which React requires to be an object and which crashes on a string
 * (minified React error #62).
 */
const PANE_CSS = `
.ofv-dsh-pane { position:absolute; inset:0; overflow:hidden; display:flex; min-height:0; }
.ofv-dsh-pane > * { flex:1 1 auto; min-width:0; min-height:0; }
.ofv-dsh-status { position:absolute; inset:0; display:flex; align-items:center;
  justify-content:center; padding:1.25rem; text-align:center; line-height:1.6;
  font-size:13px; color:var(--dsh-text-secondary, #888); }
.ofv-dsh-status[data-kind="error"] { color:var(--dsh-text-danger, #d9534f); }
`

/**
 * Inject the stylesheet once. Module materialization is memoized by the host
 * loader, so this normally runs exactly once per page load; the guard also
 * covers a double-mount across profile reloads.
 */
function installStyle(): void {
  if (styleInstalled || typeof document === 'undefined') return
  if (document.querySelector(`style[${STYLE_ATTR}]`) !== null) {
    styleInstalled = true
    return
  }
  styleInstalled = true
  const el = document.createElement('style')
  el.setAttribute(STYLE_ATTR, '')
  el.textContent = `${ofvCss}\n${PANE_CSS}`
  document.head.appendChild(el)
}

const PANE_CLASS = 'ofv-dsh-pane'
const STATUS_CLASS = 'ofv-dsh-status'

/**
 * Blob URL of the bundled pdfjs worker, built once and kept for the page's
 * lifetime: pdfjs reads `GlobalWorkerOptions.workerSrc` per document, and
 * recreating the URL would leak one object URL per rendered PDF.
 */
let pdfWorkerUrl: string | null = null
function pdfWorkerSrc(): string {
  if (pdfWorkerUrl === null) {
    pdfWorkerUrl = URL.createObjectURL(
      new Blob([pdfjsWorkerSource], { type: 'text/javascript' }),
    )
  }
  return pdfWorkerUrl
}

/**
 * Format plugins, in match order. The first matching plugin wins, so order is
 * the whole configuration:
 *
 * - `fallbackPlugin` is terminal — it matches everything, so it must be last.
 * - `officePlugin` precedes `textPlugin` so `.csv`/`.tsv` render as a
 *   spreadsheet table rather than raw delimited text.
 * - `assetPlugin` covers fonts, design files and databases; without it those
 *   suffixes match nothing and would render the fallback instead.
 */
let plugins: PreviewPlugin[] | null = null
function previewPlugins(): PreviewPlugin[] {
  plugins ??= [
    imagePlugin(),
    videoPlugin(),
    audioPlugin(),
    pdfPlugin({ pdfjs, workerSrc: pdfWorkerSrc() }),
    officePlugin(),
    epubPlugin(),
    xpsPlugin(),
    ofdPlugin(),
    archivePlugin(),
    emailPlugin(),
    drawingPlugin(),
    xmindPlugin(),
    cadPlugin(),
    model3dPlugin(),
    gisPlugin(),
    assetPlugin(),
    textPlugin(),
    fallbackPlugin(),
  ]
  return plugins
}

/** Tab type / pane body identity. Also the key on both registration seats. */
const PREVIEW_ID = 'dsh-open-file-viewer:preview'

/**
 * This type's OWN kind — deliberately not the platform's `text` kind.
 *
 * A tab kind admits one `builtin` and one `extension` at a time, and a
 * `fallback` shares its kind with nothing (see `coexists` in
 * ui-sidebar-right's tab-registry). The shipped document preview registers the
 * `text` kind in the `fallback` band, so registering `text` here — in any band
 * — makes ONE of the two throw at mount: whichever registers second loses, and
 * the user sees it reported as a plugin that failed to load.
 *
 * A distinct kind avoids the collision entirely. Types are not chosen by kind
 * but by ADDRESS: `candidates(address)` ranks every registered type by band
 * (`extension` 3 > `builtin` 2 > `fallback` 1), then by matched-pattern
 * length. Same patterns at the `extension` band therefore outrank the shipped
 * `fallback` type for every workspace file, and this kind is the one in force.
 */
const PREVIEW_KIND = 'open-file-viewer'

/** Resource address prefix for workspace files (`dsh-resource://file/…`). */
const FILE_ADDRESS_PREFIX = 'dsh-resource://file/'

/**
 * Suffixes this preview claims.
 *
 * Broader than the format plugins' own lists on purpose: the tab type decides
 * whether a file opens HERE, and `fallbackPlugin` inside the viewer renders a
 * readable notice for anything the format plugins decline. Leaving a suffix
 * out would instead send the click to the platform notice, which offers less.
 */
const EXTENSIONS = [
  // images
  'png', 'jpg', 'jpeg', 'gif', 'webp', 'avif', 'svg', 'bmp', 'ico', 'tif', 'tiff',
  'heic', 'heif',
  // video / audio
  'mp4', 'webm', 'mov', 'm4v', 'avi', 'mkv', 'flv', 'wmv', 'm3u8', 'm2ts',
  'mp3', 'wav', 'ogg', 'aac', 'm4a', 'flac', 'opus', 'mid', 'wma',
  // documents
  'pdf', 'epub', 'xps', 'oxps', 'ofd',
  'doc', 'docx', 'docm', 'dot', 'rtf', 'odt',
  'xls', 'xlsx', 'xlsm', 'xlsb', 'csv', 'tsv', 'fods', 'ods',
  'ppt', 'pps', 'pptx', 'pptm', 'odp', 'wps', 'et', 'dps',
  // text / code / config
  'txt', 'lrc', 'md', 'json', 'json5', 'yaml', 'yml', 'toml', 'ini',
  'xml', 'properties', 'env', 'log', 'sql',
  'js', 'mjs', 'cjs', 'jsx', 'ts', 'tsx', 'vue', 'svelte', 'html', 'htm', 'css',
  'scss', 'less', 'py', 'go', 'rs', 'java', 'kt', 'swift', 'c', 'h', 'cpp',
  'hpp', 'cs', 'rb', 'php', 'sh', 'bash', 'zsh', 'fish', 'lua', 'r',
  'dart', 'ex', 'exs', 'erl', 'hs', 'clj', 'scala',
  // archives
  'zip', 'rar', '7z', 'tar', 'gz', 'tgz', 'bz2', 'xz',
  // email
  'eml', 'msg', 'mbox',
  // drawings / mind maps
  'drawio', 'dio', 'excalidraw', 'tldraw', 'xmind',
  // CAD / engineering
  'dxf', 'dwg', 'dwf', 'step', 'stp', 'iges', 'igs', 'ifc', 'skp',
  'gds', 'gdsii', 'oas', 'oasis',
  // 3D
  'gltf', 'glb', 'obj', 'stl', 'fbx', 'dae', 'ply', '3mf', 'usd', 'usdz',
  // GIS
  'geojson', 'topojson', 'kml', 'kmz', 'gpx', 'shp',
  // assets
  'ttf', 'otf', 'woff', 'woff2', 'psd', 'ai', 'eps',
] as const

/** Sweep of claimed suffixes for the address-pattern veto. */
const EXTENSION_SET = new Set<string>(EXTENSIONS)

/**
 * Suffixes dsh-better-sidebar yields to the host's own previews (its
 * `HOST_OWNED_EXTS`): opens of these files from its file tree already route
 * through the native claim and land here. Everything else in
 * {@link EXTENSIONS} must ALSO be registered into better-sidebar's own
 * viewer registry, or its editor shows those files as
 * "cannot be previewed / Download to view".
 */
const BETTER_SIDEBAR_HOST_OWNED: ReadonlySet<string> = new Set([
  'xlsx', 'xls', 'csv', 'tsv', 'fods', 'pdf',
  'png', 'jpg', 'jpeg', 'gif', 'webp', 'svg', 'bmp', 'ico',
  'doc', 'docx', 'ppt', 'pptx',
])

/** Suffixes to register with dsh-better-sidebar: claimed here, not yielded. */
function betterSidebarExts(): string[] {
  return (EXTENSIONS as readonly string[]).filter(
    ext => !BETTER_SIDEBAR_HOST_OWNED.has(ext) && !BETTER_SIDEBAR_EDITABLE.has(ext),
  )
}

/**
 * Text and code suffixes that must stay with better-sidebar's editor: its
 * `code` catch-all is an EDITABLE CodeMirror with save, and its markdown /
 * html viewers add rendering this previewer (read-only) does not have.
 * Registering these here would turn every edit session into a dead preview.
 */
const BETTER_SIDEBAR_EDITABLE: ReadonlySet<string> = new Set([
  'txt', 'lrc', 'md', 'json', 'json5', 'yaml', 'yml', 'toml', 'ini',
  'xml', 'properties', 'env', 'log', 'sql',
  'js', 'mjs', 'cjs', 'jsx', 'ts', 'tsx', 'vue', 'svelte', 'html', 'htm', 'css',
  'scss', 'less', 'py', 'go', 'rs', 'java', 'kt', 'swift', 'c', 'h', 'cpp',
  'hpp', 'cs', 'rb', 'php', 'sh', 'bash', 'zsh', 'fish', 'lua', 'r',
  'dart', 'ex', 'exs', 'erl', 'hs', 'clj', 'scala',
])

/** One file reference decoded from a `dsh-resource://` address. */
interface FileRef {
  sessionId: string
  path: string
}

/**
 * Decode a `dsh-resource://file/…` address into a session id and a path.
 * Only `session`-scoped addresses are handled: an `absolute` address names a
 * file outside any session workspace, which the Remote read cannot scope.
 */
function parseFileAddress(address: string): FileRef | null {
  if (!address.startsWith(FILE_ADDRESS_PREFIX)) return null
  const query = address.search(/[?#]/)
  const body = address.slice(FILE_ADDRESS_PREFIX.length, query === -1 ? undefined : query)
  const [scope, ...rest] = body.split('/')
  if (scope !== 'session') return null
  const [rawId, ...segments] = rest
  if (rawId === undefined || rawId === '' || segments.length === 0) return null
  try {
    return {
      sessionId: decodeURIComponent(rawId),
      path: segments.map(decodeURIComponent).join('/'),
    }
  } catch {
    // A malformed percent-escape is not a file we can open.
    return null
  }
}

function baseName(path: string): string {
  const parts = path.split(/[\\/]/)
  return parts[parts.length - 1] ?? path
}

/** Whether a file's suffix is one this preview claims. */
function isClaimed(name: string): boolean {
  const dot = name.lastIndexOf('.')
  if (dot <= 0) return false
  return EXTENSION_SET.has(name.slice(dot + 1).toLowerCase())
}

interface RemoteBytes {
  readonly data: Uint8Array
  readonly eof: boolean
}

/**
 * The Typert Remote call envelope: every generated namespace method answers
 * `RemoteResult<T>`, never the business value directly — an unreachable or
 * refused read arrives as `{ ok: false, error }`.
 */
type RemoteEnvelope<T> = { readonly ok: true; readonly value: T } | {
  readonly ok: false
  readonly error: { readonly code?: string; readonly message?: string }
}

/**
 * The platform's workspace-file Remote. Only the one method used here is
 * modelled; the service carries more (stat, list, text reads).
 */
interface WorkspaceFilesRemote {
  readBytes: (
    scope: unknown,
    path: string,
    options: { range?: { offset?: number; length?: number } },
    signal: AbortSignal,
  ) => Promise<RemoteEnvelope<RemoteBytes>>
}

/**
 * Read a whole file through the Remote.
 *
 * A complete-file read (`{ range: undefined }`) is REFUSED above the
 * deployment's `maxFileBytes` (32 MiB by default) rather than truncated, and
 * one window may not exceed `maxBytes` (2 MiB), so the file is paged: the
 * first window also reports the total size, which bounds the loop and lets an
 * oversized file fail with a real message instead of a mysterious error.
 */
const WINDOW_BYTES = 2 * 1024 * 1024

/** One unwrapped byte window: envelope failures become readable errors. */
async function readWindow(
  remote: WorkspaceFilesRemote,
  ref: FileRef,
  options: { range?: { offset?: number; length?: number } },
  signal: AbortSignal,
): Promise<RemoteBytes> {
  const result = await remote.readBytes(ref.sessionId, ref.path, options, signal)
  if (!result.ok) {
    throw new Error(
      `文件读取失败（${result.error?.code ?? 'unknown'}${result.error?.message ? `: ${result.error.message}` : ''}）`,
    )
  }
  return result.value
}

async function readWholeFile(
  remote: WorkspaceFilesRemote,
  ref: FileRef,
  signal: AbortSignal,
): Promise<Uint8Array> {
  const first = await readWindow(remote, ref, {}, signal)
  if (first.eof) return first.data

  const chunks: Uint8Array[] = [first.data]
  let offset = first.data.length
  while (true) {
    const next = await readWindow(
      remote,
      ref,
      { range: { offset, length: WINDOW_BYTES } },
      signal,
    )
    if (next.data.length === 0) break
    chunks.push(next.data)
    offset += next.data.length
    if (next.eof) break
  }

  const total = chunks.reduce((sum, chunk) => sum + chunk.length, 0)
  const merged = new Uint8Array(total)
  let at = 0
  for (const chunk of chunks) {
    merged.set(chunk, at)
    at += chunk.length
  }
  return merged
}

interface ViewerHandle {
  destroy?: () => void
  resize?: () => void
}

/**
 * The dsh-better-sidebar file-viewer service face this plugin integrates
 * with (structural slice; the real contract lives in dsh-better-sidebar).
 * `registerFileViewer` contributes a previewer to the editor's own registry:
 * files opened from its file tree then render here instead of its binary
 * download fallback. Optional by design — when the plugin is absent the
 * registration is skipped and the native claim path serves everything.
 */
interface BetterSidebarService {
  registerFileViewer?: (descriptor: {
    id: string
    title?: string
    exts: readonly string[]
    priority?: number
    fetchStrategy: 'custom'
    load?: (path: string, scope: { sessionId: string }, signal?: AbortSignal) => Promise<unknown>
    component: (props: { path: string; customData?: unknown }) => unknown
  }) => () => void
}

/** Props better-sidebar hands a file viewer component (structural slice). */
interface BetterSidebarViewerProps {
  readonly path: string
  readonly customData?: unknown
}

/**
 * better-sidebar seat: mount the core viewer over the bytes the descriptor's
 * `load` fetched. The editor's own chrome stays; this draws the document
 * body only, exactly like the native pane body does.
 */
function BetterSidebarViewer({ path, customData }: BetterSidebarViewerProps) {
  const hostRef = useRef<HTMLDivElement | null>(null)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    const host = hostRef.current
    if (host === null) return
    const bytes = customData
    if (!(bytes instanceof Uint8Array) || bytes.byteLength === 0) {
      setError('文件内容读取失败')
      return
    }
    installStyle()
    host.replaceChildren()
    setError(null)
    // An OWNED ArrayBuffer (see the native pane body for why not `bytes.buffer`).
    const buffer = new ArrayBuffer(bytes.byteLength)
    new Uint8Array(buffer).set(bytes)
    const viewer = createViewer({
      container: host,
      file: buffer,
      fileName: baseName(path),
      width: '100%',
      height: '100%',
      fit: 'contain',
      toolbar: true,
      theme: 'auto',
      plugins: previewPlugins(),
    }) as ViewerHandle
    requestAnimationFrame(() => { viewer?.resize?.() })
    return () => {
      try { viewer?.destroy?.() } catch { /* already torn down */ }
      host.replaceChildren()
    }
  }, [path, customData])

  if (error !== null) {
    return createElement('div', { style: { padding: '16px', color: '#c0392b' } }, error)
  }
  return createElement('div', {
    ref: hostRef,
    style: { width: '100%', height: '100%', overflow: 'hidden' },
  })
}

/** Props the tab seat injects into a pane body. */
interface PaneBodyProps {
  readonly useTabInfo: () => { readonly tab: { readonly contentId: string } }
}

/**
 * The pane body. It owns reading the file and rendering it; the tab seat has
 * already decided that this address belongs to us.
 */
function createBodyComponent(remote: WorkspaceFilesRemote | undefined) {
  return function OpenFileViewerBody({ useTabInfo }: PaneBodyProps) {
    const hostRef = useRef<HTMLDivElement | null>(null)
    const [error, setError] = useState<string | null>(null)
    const { tab } = useTabInfo()
    const address = tab.contentId

    useEffect(() => {
      installStyle()
      const host = hostRef.current
      if (host === null) return

      const ref = parseFileAddress(address)
      if (ref === null) {
        setError('无法识别的文件地址')
        return
      }
      if (remote === undefined) {
        setError('宿主未提供文件读取服务')
        return
      }

      const controller = new AbortController()
      let disposed = false
      let viewer: ViewerHandle | null = null
      host.replaceChildren()
      setError(null)

      void (async () => {
        try {
          const bytes = await readWholeFile(remote, ref, controller.signal)
          if (disposed) return
          const fileName = baseName(ref.path)
          // An OWNED ArrayBuffer, not `bytes.buffer`: that would alias the
          // reader's storage, and `Uint8Array.buffer` types as
          // `ArrayBufferLike` (possibly shared), which the viewer's source
          // type does not accept.
          //
          // Passed raw rather than wrapped in a Blob: `normalizeFile` resolves
          // the MIME type as `mimeType || source.type || extensionMimeMap[…]`,
          // so a Blob's own type short-circuits the extension lookup and pins
          // every file to one value — images stop rendering and pdfjs stops
          // being recognised.
          const buffer = new ArrayBuffer(bytes.byteLength)
          new Uint8Array(buffer).set(bytes)
          viewer = createViewer({
            container: host,
            file: buffer,
            fileName,
            width: '100%',
            height: '100%',
            fit: 'contain',
            toolbar: true,
            theme: 'auto',
            plugins: previewPlugins(),
            onError: (err: unknown) => {
              if (!disposed) setError(err instanceof Error ? err.message : String(err))
            },
          })
          // The pane is measured after this effect in some mount orders, so
          // one deferred pass settles the initial fit.
          requestAnimationFrame(() => {
            if (!disposed) viewer?.resize?.()
          })
        } catch (err) {
          if (disposed || controller.signal.aborted) return
          setError(err instanceof Error ? err.message : String(err))
        }
      })()

      return () => {
        disposed = true
        controller.abort()
        viewer?.destroy?.()
      }
    }, [address])

    if (error !== null) {
      return createElement(
        'div',
        { className: STATUS_CLASS, 'data-kind': 'error', role: 'alert' },
        error,
      )
    }
    return createElement('div', { className: PANE_CLASS, ref: hostRef })
  }
}

/**
 * Platform services this plugin waits for.
 *
 * Required, not decorative: the loader reads `inject` to decide when to run
 * `apply`. Without it `apply` runs before the services exist, every `ctx.get`
 * answers `undefined`, and the registration silently never happens.
 *
 * `remote.workspaceFiles` is the namespace-level service the gateway provides
 * only after the api-remotes assembly mounts it — waiting on the bare `remote`
 * service races the mount and captures `workspaceFiles` as undefined.
 */
const inject = ['slots', 'sidebarRightTabs', 'remote', 'remote.workspaceFiles']

interface Slots {
  inject: (name: string, factory: () => void) => void
  register: (descriptor: unknown, component: unknown) => () => void
}

interface TabRegistry {
  register: (definition: unknown) => () => void
}

interface ClientContext {
  effect: (fn: () => (() => void) | void, label?: string) => void
  get: (name: string) => unknown
}

/** Client plugin body. */
function apply(ctx: ClientContext): void {
  installStyle()

  ctx.effect(() => {
    const slots = ctx.get('slots') as Slots | undefined
    const tabs = ctx.get('sidebarRightTabs') as TabRegistry | undefined
    const remote = ctx.get('remote') as { workspaceFiles?: WorkspaceFilesRemote } | undefined
    if (slots === undefined || tabs === undefined) {
      console.warn('[dsh-open-file-viewer] platform services are not available')
      return
    }

    const component = createBodyComponent(remote?.workspaceFiles)
    const disposers: (() => void)[] = []

    // Stage one: claim workspace file addresses at the highest band. The kind
    // is this plugin's own, so the shipped `text` type keeps its registration
    // and only loses the RANKING for these addresses.
    disposers.push(
      tabs.register({
        id: PREVIEW_ID,
        kind: PREVIEW_KIND,
        patterns: ['dsh-resource://file/**'],
        priority: 'extension',
        canOpen: (address: string) => {
          const ref = parseFileAddress(address)
          return ref !== null && isClaimed(baseName(ref.path))
        },
        title: (address: string) => {
          const ref = parseFileAddress(address)
          return ref === null ? address : baseName(ref.path)
        },
      }),
    )

    // Stage two: the body, under the type id the seat dispatches.
    slots.inject('sidebar.right.pane.tab', () => {
      disposers.push(
        slots.register({ name: 'sidebar.right.pane.tab', key: PREVIEW_ID }, component),
      )
    })

    // Stage three: dsh-better-sidebar's editor claims file opens from its own
    // file tree with an extension-band registration of its own, then renders
    // from its PRIVATE viewer registry — without a registration there, every
    // format outside its HOST_OWNED_EXTS (3D, CAD, GIS, media, archives)
    // lands on its "cannot be previewed" download face. Contribute this
    // previewer through its public `registerFileViewer` so those opens render
    // here. The service is optional: when the plugin is absent the short
    // poll below gives up and the native claim path keeps serving every
    // surface that routes through it.
    const filesRemote = remote?.workspaceFiles
    let clearBetterSidebarPoll: (() => void) | undefined
    if (filesRemote !== undefined) {
      let pollTimer: ReturnType<typeof setTimeout> | undefined
      let pollsLeft = 30
      const registerIntoBetterSidebar = (): void => {
        pollTimer = undefined
        const betterSidebar = ctx.get('betterSidebar') as BetterSidebarService | undefined
        const register = betterSidebar?.registerFileViewer
        if (register === undefined) {
          // Retry while the service is missing — better-sidebar may activate
          // after this plugin. Without a timer in this realm (the standalone
          // verify sandbox) retrying is impossible; give up and leave the
          // native claim path to serve every open.
          if (pollsLeft > 0 && typeof setTimeout === 'function') {
            pollsLeft -= 1
            pollTimer = setTimeout(registerIntoBetterSidebar, 500)
          }
          return
        }
        disposers.push(register({
          id: PREVIEW_ID,
          title: 'Open File Viewer',
          exts: betterSidebarExts(),
          priority: 10,
          fetchStrategy: 'custom',
          load: (path: string, scope: { sessionId: string }, signal?: AbortSignal) =>
            readWholeFile(filesRemote, { sessionId: scope.sessionId, path }, signal ?? new AbortController().signal),
          component: BetterSidebarViewer,
        }))
        console.info('[dsh-open-file-viewer] registered the previewer with dsh-better-sidebar')
      }
      registerIntoBetterSidebar()
      clearBetterSidebarPoll = () => { if (pollTimer !== undefined) clearTimeout(pollTimer) }
    }

    console.info('[dsh-open-file-viewer] claimed the document preview kind', PREVIEW_ID)

    return () => {
      clearBetterSidebarPoll?.()
      for (const dispose of disposers.reverse()) {
        try {
          dispose()
        } catch {
          /* a seat already torn down is not an error */
        }
      }
    }
  }, 'dsh-open-file-viewer: document preview registration')
}

export { apply, inject, PREVIEW_ID, PREVIEW_KIND, EXTENSIONS }
